call plug#begin('~/.vim/plugged')

Plug 'tpope/vim-fugitive'
Plug 'scrooloose/syntastic'
Plug 'tpope/vim-surround'
Plug 'morhetz/gruvbox'
Plug 'rhysd/vim-clang-format'
Plug 'vim-airline/vim-airline'
Plug 'ludovicchabant/vim-gutentags'
Plug 'Rip-Rip/clang_complete'
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'

call plug#end()

set nocompatible

set path+=.,/usr/include,/usr/include/c++/7,**
set wildmenu

syntax enable

set number relativenumber

set syntax=on
set termguicolors
set background=dark
colorscheme gruvbox

set hlsearch
set incsearch
set ignorecase
set smartcase
:nnoremap <C-L> :nohlsearch<CR>:ClangFormat<CR><C-L>

set tabstop=4
set shiftwidth=4
set smarttab
set expandtab

let g:clang_format#code_style = "llvm"

let g:clang_library_path='/usr/lib/llvm-6.0/lib/libclang.so.1'
let g:clang_auto_select=1
let g:clang_jumpto_declaration_key='<C-\>'

let g:gutentags_ctags_extra_args=['--c++-kinds=+p','--fields=+iaS','--extras=+fq']

let g:syntastic_c_cppcheck_args = "-I/usr/include"

let g:UltiSnipsExpandTrigger='<C-J>'
let g:UltiSnipsListSnippets="<C-Z>"
