if command -v tmux &> /dev/null && [ -z "$TMUX" ]; then
    tmux attach -t default || tmux new -s default
fi

alias sudo='sudo '
alias e=nvim
alias ec="nvim ~/.config/nvim/init.vim"

export GTEST_COLOR=1
